### ISSUE TITLE
[ShovelKnight] tv resolution is 1080p not 720p

### ISSUE THREAD

**Issue by ppsspp213** [slashiee/cemu_graphic_packs#20]
f4000800_fmt001a_mip00_1920x1080_tm04_sw00000000.bmp 
f5188000_fmt001a_mip00_1600x960_tm04_sw00000000.bmp
f4ff2800_fmt001a_mip00_854x480_tm04_sw00000000.bmp
13cb0900_fmt001a_mip00_512x512_tm01_sw00000000.bmp = background
13b43500_fmt001a_mip00_432x244_tm01_sw00000000.bmp = logo at the original games resolution
12068400_fmt001a_mip00_256x256_tm01_sw00000000.bmp = icons and japanese text
12c23e00_fmt001a_mip00_96x140_tm01_sw00000000.bmp = diggable mound
12b18400_fmt001a_mip00_88x76_tm01_sw00000000.bmp = weapon sprites

**Comment by slashiee** [comment]
Fixed with 6321fd7

**Comment by ppsspp213** [comment]
The games resolution seems to be 1024x1024, notice the health bar cuts off otherwise.

**Comment by slashiee** [comment]
Is there any photo of that problem?

**Comment by ppsspp213** [comment]
https://gbatemp.net/threads/release-cemu-wii-u-emulator.399524/page-908#post-7029452

I found a rule that effects the health bar but it still doesn't scale
properly, infact writing rules for alot the textures just makes them appear
black.

**Comment by slashiee** [comment]
I would test the game without any graphic packs first. If it's still present with graphic packs off, then it's Exzap's issue, not mine.

**Comment by Darkemaste** [comment]
Just looked into this issue, there was another [unique] resolution that the game uses that I was able to find in GPUPerfStudio.  You don't need to mess with any other textures/formats/maps/sprites themselves.

The cut off health bar and line through the text in the menu isn't a graphic pack issue however, it can be noted at native resolution/without a graphic pack. (this can't be fixed by graphic packs)

The fix will be included in my next PR.

**Comment by slashiee** [comment]
This ***should*** be fixed as of #23
