### ISSUE TITLE
Super Smash Bros. [AXF#01]

### ISSUE THREAD

**Issue by Shunreal** [slashiee/cemu_graphic_packs#42]
![nvidia](https://cloud.githubusercontent.com/assets/26977947/24770508/73d3b64e-1b0a-11e7-841a-6af0fc0b6235.jpg)

https://abload.de/img/nvidiaphp4c.jpg

This happens when both graphic packs are activated.

**Comment by slashiee** [comment]
AFAIK Cemu seems to have issues when having the workaround pack and the actual graphic packs enabled at the same time. If the workaround doesn't screw over AMD, then I'll implement the workaround into the main packs themselves.

**Comment by slashiee** [comment]
Here's a test pack, I'm assuming you're using 4K.
```
[Definition]
titleIds = 0005000010110E00,0005000010145000,0005000010144F00,ffffffffd72e798a
name = "Super Smash Bros. - 2160p (4K)"

[TextureRedefine] # tv
width = 1920
height = 1080
formatsExcluded = 0x219
overwriteWidth = 3840
overwriteHeight = 2160

[TextureRedefine] # NVIDIA Fix
width = 1920
height = 1080
formats = 0x219
overwriteFormat = 0x820
overwriteWidth = 3840
overwriteHeight = 2160

[TextureRedefine] # half-res
width = 960
height = 540
overwriteWidth = 1920
overwriteHeight = 1080

[TextureRedefine] # q-res
width = 480
height = 270
overwriteWidth = 962
overwriteHeight = 542

[TextureRedefine] # o-res 
width = 240
height = 135
overwriteWidth = 481
overwriteHeight = 271

[TextureRedefine] # half-res 2
width = 120
height = 67
overwriteWidth = 240
overwriteHeight = 134

[TextureRedefine] # q-res 2
width = 60
height = 33
overwriteWidth = 120
overwriteHeight = 66

[TextureRedefine] # o-res 2
width = 30
height = 16
overwriteWidth = 60
overwriteHeight = 32

[TextureRedefine] # o-res 3
width = 8
height = 1
overwriteWidth = 16
overwriteHeight = 2

[TextureRedefine] # 2nd
width = 820
height = 410
overwriteWidth = 1640
overwriteHeight = 820

[TextureRedefine] # 3rd
width = 730
height = 365
overwriteWidth = 1460
overwriteHeight = 730

[TextureRedefine] # 4th
width = 420
height = 210
overwriteWidth = 840
overwriteHeight = 420

**Comment by Shunreal** [comment]
It works

![fixed](https://cloud.githubusercontent.com/assets/26977947/24779125/987f4e80-1b2e-11e7-857b-f4adf8a0a572.jpg)

https://abload.de/img/fixedxcqkc.jpg

**Comment by slashiee** [comment]
I've tested the NVIDIA workaround on AMD, no issues to be found. I think it's safe to push the fix to the main packs.

**Comment by slashiee** [comment]
Fixed as of c9bf586

**Comment by slashiee** [comment]
Nevermind apparently still broken on 1.7.5, image is from a friend
![image](https://cloud.githubusercontent.com/assets/15317421/25604615/a1b4be4c-2eb9-11e7-82bc-22abadf4286f.png)

**Comment by slashiee** [comment]
This might be fixed with 1.7.6's proper gl_FragCoord scaling. I will check to make sure that this is the case. If it is fixed, I will close this issue when 1.7.6 releases publicly.

**Comment by slashiee** [comment]
Apparently this issue didn't happen for some in 1.7.5, but I'm getting the same friend to test in 1.8.0 to see if his issue is fixed. If so, I'll be closing this
